---
apiVersion: v1
kind: Service
metadata:
  name: bullish
  labels:
    app: bullish
spec:
  type: NodePort
  selector:
    app: bullish
  ports:
    - protocol: TCP
      port: 8080
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bullish
spec:
  selector:
    matchLabels:
      app: bullish
  replicas: 2
  template:
    metadata:
      labels:
        app: bullish
    spec:
      containers:
        - name: bullish
          image: seanzhu0925/bulishapi-docker:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1